package org.shadownova.vollzanbel.dto

import com.fasterxml.jackson.annotation.JsonProperty

/** Typed snapshot contract. JSON names match the multiplatform client and legacy stored sheets. */
data class CharacterSheet(
    val name: String,
    val characterClass: String,
    val subclass: String = "",
    val level: Int,
    val experiencePoints: Int = 0,
    val ruleSet: RuleSet = RuleSet.DND_2014,
    @param:JsonProperty("race") @get:JsonProperty("race") val species: String,
    val subrace: String = "",
    val background: String = "",
    val hp: HitPoints,
    val ac: Int,
    val stats: CharacterStats,
    val proficiencyBonus: Int,
    val skills: List<SkillProficiency>,
    val savingThrows: List<SavingThrowProficiency>,
    val spellSlots: Map<Int, SpellSlotInfo> = emptyMap(),
    val resources: List<TrackedResource> = emptyList(),
    val journal: List<JournalEntry> = emptyList(),
    val effects: List<CharacterEffect> = emptyList(),
    val combat: CombatState = CombatState(),
    val inventory: List<EquipmentItem> = emptyList(),
    val spells: List<Spell> = emptyList(),
    val spellcastingInfo: SpellcastingInfo = SpellcastingInfo(),
    val profile: CharacterProfile = CharacterProfile(),
    val heroicInspiration: Boolean = false,
    val hitDice: HitDice = HitDice(),
    val deathSaves: DeathSaves = DeathSaves(),
    val classFeatures: List<ClassFeature> = emptyList(),
    val speciesTraits: List<SpeciesTrait> = emptyList(),
    val feats: List<Feat> = emptyList(),
    val weaponMasteries: List<WeaponMastery> = emptyList(),
    val languages: List<String> = emptyList(),
    val armorTraining: ArmorTraining = ArmorTraining(),
    val weaponTraining: WeaponTraining = WeaponTraining(),
    val currency: Currency = Currency(),
    val hasShield: Boolean = false,
    val speed: Int = 30,
    val conditions: Set<String> = emptySet(),
    val exhaustionLevel: Int = 0,
    val pendingLevelUp: PendingLevelUp? = null,
)
